# machine generated by MqttServer

import sys, os
sys.path.append(os.path.expandvars('$IOT_PROJECTS/plotserver/lib'))

from line_plot import LinePlot
from bokeh.plotting import curdoc

args = [['time', 'y'], 50, 0.1]
kwargs = {'title': 'Awesome sinusoid'}

lp = LinePlot("sin", *args, **kwargs)
lp.app(curdoc())

print(f"serving sin at http://pi4server.home/plotserver/sin")
